### PR TITLE
Add CMIP6 datatree sample

### PR DESCRIPTION
**Pull request by andersy005**
- Towards https://github.com/xarray-contrib/datatree/issues/100
- Notebook used to generate this dataset: https://github.com/andersy005/brouillons-quotidien/blob/main/datatree/cmip6-sample.ipynb

Cc @TomNicholas

### CODE REVIEW

**Comment by keewis** [comment]
just wondering: should we put datatree examples into their own subdirectory? At the moment, anything in the repository root is picked up by `xr.tutorial.open_dataset`.

**Comment by andersy005** [comment]
👍 for a separate folder

**Comment by kmuehlbauer** [comment]
@andersy005 For some reason your change is already committed in master, but this PR still exists.

**Comment by andersy005** [comment]
> @andersy005 For some reason your change is already committed in master, but this PR still exists.

interesting... not sure how they got there. perhaps someone else added them. happy to close this one to reduce noise

**Pull request closed without merging**
